export type ListingOverviewRow = {
  listing_id: string;
  source: string;
  source_listing_id: string | null;
  url: string;
  title: string;
  brand: string | null;
  model: string | null;
  trim: string | null;
  price: number | null;
  year: number | null;
  mileage: number | null;
  transmission: string | null;
  fuel: string | null;
  city: string | null;
  seller_type: string | null;
  photo_url: string | null;
  fetched_at: string;
  last_seen_at: string;
  fit_score: number | null;
  practicality_score: number | null;
  deal_score: number | null;
  total_score: number | null;
  positive_tags: string[] | null;
  caution_tags: string[] | null;
  exception_reason: string | null;
  scoring_version: string | null;
  favorite: boolean | null;
  shortlisted: boolean | null;
  rejected: boolean | null;
  notes: string | null;
  user_state_updated_at: string | null;
};
